### ISSUE TITLE
Zooming in on picture review?

### ISSUE THREAD

**Issue by mnalis** [Helium314/SCEE#392]
**Use case**

In [v48.0-beta1_ee](https://github.com/Helium314/StreetComplete/releases/tag/v48.0-beta1_ee)  there is now a option to see picture that was taker for a note! 

BTW is that original picture, or downsized one (i.e. the one that would be sent to the server) ?

**Proposed Solution**

If that is (hopefully) same picture which would be uploaded to server and downloaded by other users later, it would be great to allow zooming in/out the picture to check if texts on it are actually readable (e.g. addresses, opening hours, etc).

That would basically implement https://github.com/streetcomplete/StreetComplete/issues/2497, so might be even PR'd to the upstream.

**Comment by Helium314** [comment]
That's the image SC uses (resized to max 1280 pixels).
I didn't find any way to make zoom work in a simple way, and decided that the current state is still an improvement over the micro-image.

**Comment by Helium314** [comment]
@westnordost
I solved this using https://github.com/Baseflow/PhotoView, because it seems normal Android(x) libraries have no implementation of some sort of pan/pinch-zoom image view.

If yet another (potentially unmaintained) library is acceptable in StreetComplete, I can make a PR.

**Comment by westnordost** [comment]
Hm, I can't imagine how the UI works in practice... you zoom in the thumbnail by pinching it? Would you mind adding a video?

Using a dependency for that makes sense. Last update of PhotoView was from 5 years ago though, an countless open PRs and issues.

**Comment by Helium314** [comment]
No screen record, but I hope this is enough. You click the thumbnail (which has no `x` any more), and see:
![Screenshot_20230130-140505_SCEE_Dev](https://user-images.githubusercontent.com/43007630/215485905-cb54e761-12f7-4e5a-9531-63bb31ce2ff8.png)

The entire dialog area above the buttons is used for the image if you zoom.

**Comment by Helium314** [comment]
>  Last update of PhotoView was from 5 years ago though, an countless open PRs and issues.

2.3.0 is a little bit newer (November 2018) and at least doesn't require jetifier like the 2.0.0 GitHub release does, but yes... a more maintained library is preferable.

**Comment by westnordost** [comment]
Ah I see, it is shown in a dialog. Could have been too that x deletes the photo and tapping anywhere else on the thumbnail opens a dialog with a completely custom view (no dialog frame) that only shows the zoomed picture or something. IIRC it was kind of straightforward to do (not using AlertDialogBuilder). For example. Probably this is how I would have implemented it instinctively, but not sure if this is better.

In any case, looks useful to me either way.

Can't comment on TouchImageView.

**Comment by Helium314** [comment]
TouchImageView doesn't work. Looks like there are some Kotlin version issues with 1.7.10 used by SC and 1.8.0 used by TouchImageView.

So you mean just showing the image on darkened background, without the dialog?

**Comment by westnordost** [comment]
Without the alert dialog,  yes.  As far as i remember it would still be a Dialog

**Comment by Helium314** [comment]
Looks like what you described when I set the background to transparent.
But I didn't manage to close the dialog when tapping anywhere outside the image (back press is needed).

**Comment by westnordost** [comment]
Because I presume while transparent, the alert dialog window background is still there?

**Comment by Helium314** [comment]
Actually the issue was that the PhotoView takes up the entire dialog. But it has an `OnOutsidePhotoTapListener` that does the job.

So on touching the tumbnail, the dialog should be shown, and on touching the delete button (`x`) the image should be deleted?

**Comment by westnordost** [comment]
Yeah, I think that would be the best UX. The minimum recommended size for buttons is 48x48dp. So if the X button alone is a little small then, I'd suggest to increase the size of the thumbnail+X button overall
