### ISSUE TITLE
Counter Last Days doesn't work

### ISSUE THREAD

**Issue by ineubert** [Helium314/SCEE#401]
If I use the Expert Edition and add some Information to OSM, the counter for "Last 7 days" and also "When you have mapped in the last time" isn't working.
If I do this with the "normal" App (mo Expert Edition) it works as expected.

Android 13
Street Complete v49.0_ee

**Comment by r1llettes** [comment]
Same here, changes are uploaded to OSM but not counted anywhere in the app.

**Comment by mnalis** [comment]
> Same here, changes are uploaded to OSM but not counted anywhere in the app.

- Changes made with SC EE are **_not supposed to be counted_**, see https://github.com/Helium314/StreetComplete/issues/370 and `README.md`:

  https://github.com/Helium314/StreetComplete/blob/43ca39126855ec1ea8a8fbf148a9a1429ca6b336/README.md?plain=1#L19


- But the counting of regular StreetComplete quests should be shown normally _usually_. However, note that **currently there is rebuild in progress in upstream StreetComplete**: https://github.com/streetcomplete/StreetComplete/issues/4625 so your statistics may or may not show currently in either the upstream SC or SC EE fork. (especially if you logout and login again)

**Comment by Helium314** [comment]
> * Changes made with SC EE are **_not supposed to be counted_**, see [quest count for the modified version #370](https://github.com/Helium314/StreetComplete/issues/370) and `README.md`:
>       https://github.com/Helium314/StreetComplete/blob/43ca39126855ec1ea8a8fbf148a9a1429ca6b336/README.md?plain=1#L19

Plus the message you see on first start: https://github.com/Helium314/StreetComplete/blob/7c91e543e035df8bf79f435764a4cf71f3981e6e/app/src/main/res/values/strings_ee.xml#L322

> But the counting of regular StreetComplete quests should be shown normally usually.

Right, actually it should count edits made in regular StreetComplete, as this is where the statistics are taken from.
Is the "last 7 days" not working at all, or just not counting edits made in EE?

----

I was thinking recently whether statistics could be somehow enabled, as the new "last 7 days" might also be interesting locally. Some ideas:
* Set up a [statistics service](https://github.com/streetcomplete/sc-statistics-service) for EE: will not count edits in regular SC, though it might be simple to sum up edits of both SC versions
* Get and sum up edits from OSM changesets locally (on the phone): similar as above, but there will not be any ranking
  * probably requires more work than setting up the statistics service, but doesn't need a server
* Disable synchronisation with statistics service and only use on-device data: least amount of work, and statistics should work (untested). But all statistics will be lost when re-installing SC EE, and there is no ranking.

Anyway, I am not really interested in those statistics, so I don't want to spend (much) time on this. If anyone is interested or has an idea that's better / simpler than mine, contribution is welcome.

**Comment by Helium314** [comment]
Statistics will work starting from next version
