### ISSUE TITLE
"All quest types related to roads / paths may add access=private"

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#407]
https://github.com/Helium314/SCEE#changeset-differences-compared-to-streetcomplete

Seems to not apply: https://github.com/Helium314/SCEE/commit/ae65fce9a8614d7e8d9d2c334c554bbd07eb642a - and https://github.com/Helium314/SCEE/blob/modified/app/src/main/java/de/westnordost/streetcomplete/quests/smoothness/AddPathSmoothness.kt seems to be the current state

**Comment by Helium314** [comment]
I removed it from the individual quest forms and went for a more generic approach:
https://github.com/Helium314/SCEE/blob/7dadb0b434b64e3a4d2d3b5d2d3e5cccbe3840a8/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractOsmQuestForm.kt#L351-L378
It looks like I hid this in some generic "fix build" commit, not sure why.
