### ISSUE TITLE
proposal: change repository description

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#410]
https://github.com/Helium314/SCEE

Maye "StreetComplete expanded with more complicated editing features, not intended for users new to OpenStreetMap"?

**Comment by Helium314** [comment]
Umm, where can I find this repository description?

**Comment by matkoniecz** [comment]
![Peek 2023-02-09 16-11](https://user-images.githubusercontent.com/899988/217852136-7699dd02-1b4c-4599-ab45-398652b8b6a6.gif)

**Comment by Helium314** [comment]
Ah I see, thanks.
I hadn't even noticed this description.

**Comment by Helium314** [comment]
Changed to description from [metadata](https://github.com/Helium314/SCEE/blob/modified/metadata/en-US/short_description.txt): "OpenStreetMap surveyor app for experienced OSM contributors"
