### ISSUE TITLE
Ask for shop type not only for shop=yes but also for shops with unclear values

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#411]
I though about implementing something like that in my fork, maybe would be welcome also here?

Note that it would likely require maintaining long list of valid shop values (I would write script listing all shops with OSM Wiki pages or find already existing one doing this)

It cannot go into base SC as often the correct solution would be documenting shop value on OSM Wiki or inventing a new tagging scheme to retag shop as subtype of more widely used value

See https://taginfo.openstreetmap.org/keys/shop#values (`shop=Mapbox`, `shop=opał` etc)

**Comment by Helium314** [comment]
Sure, if you're doing it anyway your'e welcome to add it to SCEE too!
This could probably be added to `SpecifyShopType`. Though then the question should also contain the current value of `shop`.

**Comment by matkoniecz** [comment]
> Though then the question should also contain the current value of shop.

Do we have way to do this? (in my `fixme` showing quest I use some kind of hack to do this, do not remember which one - probably it can be used also here)

**Comment by Helium314** [comment]
Default way is
https://github.com/Helium314/SCEE/blob/249b0d402294afd57fab78585221004e44bc80f0/app/src/main/java/de/westnordost/streetcomplete/data/osm/osmquests/OsmElementQuestType.kt#L62-L68
But you can also set the title in the form, I think this is done in `OsmoseForm`
https://github.com/Helium314/SCEE/blob/249b0d402294afd57fab78585221004e44bc80f0/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractQuestForm.kt#L164

**Comment by Helium314** [comment]
In https://github.com/Helium314/SCEE/commit/a4b868b81893421759e5c93712cdfa93ca73f67b I added showing the tag, and asking for some additional types as per [wiki](https://wiki.openstreetmap.org/wiki/Key:shop#Possible_tagging_mistakes).
You would only need to extend the element selection once the list is done.

**Comment by matkoniecz** [comment]
I am attacking this specific problem from a bit different direction, see https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/fixing_malformed_shop_tags

Unless someone will start protesting (not happened so far) on 11 III or few days later `shop=shop` `=other` `=unknown` will be retagged and any new ones also will be.

Added `retail` to the next iteration.

`shop=fixme` is unspecific and seems not viable for autoreplacement.

**Comment by Helium314** [comment]
Alright, so we can still use the quest for values where bot edit is not good.

**Comment by matkoniecz** [comment]
There is a progress!

-------------------------------------------------------------------------------------------

On review of tagging situation: asking for open-ended list of all shops will not work well. But asking for known problematic ones like `shop=hobby` should work.

-------------------------------------------------------------------------------------------

If anyone is interested in specifics of progress, see https://gitlab.com/matkoniecz/osm-automation/-/blob/master/detect_unhandled_invalid_shop_values.py where investigated values not ready for bot edit are listed

If anyone is interested in helping:

`shop=patisserie` and `shop=Tienda_y_taller_de_articulos_de_greda` would benefit from someone local researching situation and fixing them or contacting author or documenting as valid

`shop=souvenirs` - should it be documented as valid or retagged to `shop=gift` (requires discussion on tagging mailing list or OSM forum)

`shop=stamps`, `shop=gravestone` / `shop=tombstone` / `shop=soap` / `shop=fireworks`  document on wiki as valid? Is there a replacement for them? Note `gravestone` vs `tombstone` (requires research and/or fnding alternatives and/or discussion)

`shop=chandler`, `shop=chandlery` - should it be replaced with `shop=ship_chandler` in a bot edit? If no, why? (not sure should I propose it in the next bot edit)

**Comment by matkoniecz** [comment]
I am still working on it but:

- it will be definitely closed list of values, not all undocumented values (maybe years/decades in future we will have coverage of various shop types that gives alternative to having long tail with stuff like `shop=asparagus` and `shop=trout`)
- it will be in StreetComplete so it will arrive here via merging in upstream

Currently works takes place in https://gitlab.com/matkoniecz/osm-automation/-/blob/master/detect_unhandled_invalid_shop_values.py and https://gitlab.com/matkoniecz/osm-automation/-/blob/master/script_assisted_cleanup/shops_fix_bad_values.py and https://gitlab.com/matkoniecz/osm-automation/-/blob/master/recurrent_bot_edits/NEXT_shops_fix_bad_values.py and https://gitlab.com/matkoniecz/osm-automation/-/blob/master/recurrent_bot_edits/shops_fix_bad_values.py

Of anyone is interested in help in reviewing existing not documented shop values but is unsure how: write to matkoniecz@tutanota.com (or participate in threads I keep posting in https://community.openstreetmap.org/c/general/tagging/70 )
