### ISSUE TITLE
"it is private" seems useful also for some other quests

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#412]
For example one asking about `leisure=track` surface (it was track in a military base https://www.openstreetmap.org/changeset/132535766 )

**Comment by Helium314** [comment]
Yes, this could be expanded. Do you have some more suggestions?
Sports pitches and recycling containers should also have this option.

**Comment by matkoniecz** [comment]
I encountered also benches but it seems that private benches are not filtered out (not checked SC code so far)

**Comment by Helium314** [comment]
Right, private benches are not excluded from the backrest quest... though I guess they should be?

**Comment by matkoniecz** [comment]
> Right, private benches are not excluded from the backrest quest... though I guess they should be?

probably should be also in SC itself, if they are not already
