### ISSUE TITLE
Add possibility to create nodes as part of way

### ISSUE THREAD

**Issue by nlehuby** [Helium314/SCEE#414]
**Use case**
I have used the "Add POI" button to create a barrier on some footpath. But the app has only created an isolated node, instead of vertex, a node that is part of the actual way, as an obstacle on the footpath.

It would also be useful to create entrance nodes (as part of building way)

**Proposed Solution**
We can know about the nodes that can be vertexes from ID presets. So maybe a "snap to way" button on the POIs that could be vertex, that highlights nearby ways add let you choose one of them ?

**Comment by Helium314** [comment]
This is planned to be implemented, but only once the create vertex thing is actually implemented in StreetComplete.
See the [create-vertices branch](https://github.com/streetcomplete/StreetComplete/compare/master...create-vertices), (and the two experimental branches) which also contains comments on why implementing this is not so simple.

**Comment by nlehuby** [comment]
Ok, thanks !

Do you know what the use case is in StreetComplete ? I could not find any issues linked to these branches :thinking:

**Comment by Helium314** [comment]
Not specifically, there might be an idea for an overlay.
A bit more information on the issues of implementing this: https://github.com/streetcomplete/StreetComplete/pull/4481

**Comment by Helium314** [comment]
A light version of this is coming with the next update.
You can create a node that is part of exactly one way, which should be enough for things like missing crossings.

Other things like connecting 2 crossing ways still need to wait until the functionality is implemented properly.
