### ISSUE TITLE
"Due to the different name used in changesets" -> "Due to extra features that may significantly affect how objects are edited"

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#415]
https://f-droid.org/en/packages/de.westnordost.streetcomplete.expert/ has

> Due to the different name used in changesets, edits made with this version do not contribute to the displayed StreetComplete statistics and star count.

but that is just a technical method, not actual reason for that

Maybe

> Due to extra features that may significantly affect how objects are edited, edits made with this version do not contribute to the displayed StreetComplete statistics and star count.

would be better?

I would make a PR but failed to locate where this text is defined, even if it is defined in the repository

**Comment by Helium314** [comment]
Sure, that sounds good and makes sense.
F-Droid description is in https://github.com/Helium314/SCEE/blob/modified/metadata/en-US/full_description.txt
