### ISSUE TITLE
Allow answering "1" for two-way roads with an obvious lane count but without markings

### ISSUE THREAD

**Issue by matkoniecz** [Helium314/SCEE#420]
https://www.google.pl/maps/@50.1440269,19.9084778,3a,75y,154.07h,74.44t/data=!3m6!1e1!3m4!1sVMT2md9QADrtfvRA7dHkew!2e0!7i13312!8i6656

this is present already in my Zażółć fork (if accepted may try to submit PR, though no promises on doing it immediately)

![screen03](https://user-images.githubusercontent.com/899988/222969445-8353e726-3e21-4803-9b0d-3154bfa3c737.png)

**Comment by Helium314** [comment]
Sure, the current "obvious lane count but without markings" stuff is taken from Zażółć anyway, so keeping the SCEE copy of this up to date makes sense.
