### ISSUE TITLE
What kind of markings does this crossing have?

### ISSUE THREAD

**Issue by ivanbranco** [Helium314/SCEE#425]
Hi, I was wondering if you have considered to add a quest like this, since [it was rejected](https://github.com/streetcomplete/StreetComplete/issues/4663) from StreetComplete.
I tried editing the POI: Traffic quest adding a "and !crossing:markings" but is still a slow procedure and a quest would make everything easier.

**Comment by Helium314** [comment]
Sure, this could be added to SCEE.
Probably should be asked for something like
```
        nodes with
          crossing
          and (
            crossing:markings = yes
            or (crossing ~ marked|uncontrolled|traffic_signals and !crossing:markings)
          )
          and !crossing_ref = zebra
```
Maybe it should not be asked for countries where markings are always the same / can be determined from other tags.

@mnalis I vaguely remember you showed something like a crossing that is zebra but legally not actually zebra (?). Could this be relevant here?

**Comment by ivanbranco** [comment]
> and !crossing_ref = zebra

Uhm, the crossing_ref value wasn't very detailed, if I'm not wrong crossing_ref=zebra could correspond to different crossing_markings=* values (zebra, zebra:double,zebra:paired ecc.), so think it shouldn't be excluded from the quest.

**Comment by Helium314** [comment]
That's actually another thing that may depend on country, and can be decided by whoever implements the quest.

**Comment by mnalis** [comment]
> @mnalis I vaguely remember you showed something like a crossing that is zebra but legally not actually zebra (?). Could this be relevant here?

Hmmm, I don't quite remember; might it have been someone else? 

We do have issues with segregated footway+cycleway crossings which** should be for both pedestrians** (marked with white&black zebra stripes) **and bicycles** (marked with continuous red track), but sometimes **only** pedestrian zebra is marked (so bicyclist are legally required to dismount and cross as pedestrians, and then mount the bicycle again) - i.e. legally bicycle path ends just before crossing, and then new bicycle path starts few meters after crossing again.

But that problem is not tagged with `crossing:markings=*` here, but instead with `bicycle=dismount`  on such crossings ways.

**Comment by Helium314** [comment]
Actually I think this is more or less accepted in SC: https://github.com/streetcomplete/StreetComplete/issues/4886#issuecomment-1485667735

It will not be asked if there is a `crossing` tag, but that's something you will be able to change in (SCEE) quest settings.

**Comment by Helium314** [comment]
SC has now switched to ask yes/no for markings and signals at crossings.
Instead of adding another quest, a settings could be added which allows the user to specify the markings instead of answering yes/no.

**Comment by mcliquid** [comment]
@Helium314 If I prepare the quest as a regular image selection (AImageListQuestForm), could you take over the implementation with the setting? I assume that I won't be figure this out.

**Comment by Helium314** [comment]
It should be possible to allow selecting the quest form based on `prefs`, that would be a simply way.

The current yes/no form would need to be switched for a slightly modified copy that returns a string instead of a boolean.

**Comment by Helium314** [comment]
Adding a quest setting for this is simple, but I can do it

**Comment by ravenfeld** [comment]
Would you like me to suggest a PR with a selection of images from the wiki https://wiki.openstreetmap.org/wiki/FR:Key:crossing:markings ?

I didn't understand where you wanted to put the parameter.

**Comment by mcliquid** [comment]
> Would you like me to suggest a PR with a selection of images from the wiki https://wiki.openstreetmap.org/wiki/FR:Key:crossing:markings ?

Personally, I would be more than happy! Let me suggest you the [english version](https://wiki.openstreetmap.org/wiki/Key:crossing:markings) of the wiki because it has more pictures of values / examples.

**Comment by ravenfeld** [comment]
given that adobe only uses a 526, maybe so. 
It looks specific to your region and you don't use it, do you?   

https://en.wikipedia.org/wiki/Adobe

**Comment by mcliquid** [comment]
> given that adobe only uses a 526, maybe so.
> It looks specific to your region and you don't use it, do you?

Never heard of it. The closest thing we have ([DACH ](https://en.wiktionary.org/wiki/DACH)region) is [brick](https://en.wikipedia.org/wiki/Brick).

**Comment by ravenfeld** [comment]
> > given that adobe only uses a 526, maybe so.
> > It looks specific to your region and you don't use it, do you?
> 
> Never heard of it. The closest thing we have ([DACH ](https://en.wiktionary.org/wiki/DACH)region) is [brick](https://en.wikipedia.org/wiki/Brick).


Sorry bad subject I deleted.

**Comment by ravenfeld** [comment]
That's a lot of cases and, above all, how do you manage difficult cases? Are they all managed? 
Maybe make images like the classic cases for the difficult ones?
Or would it be better to do just the classic cases?

**Comment by mcliquid** [comment]
I would go with the currently most used entries, as I often do. As the implementer, you can determine the number yourself :)
Compared to the normal surface-Quest, there are over 20 pictures to choose from.
My personal list would be the following (sorted by usage, min. 1000):
zebra, lines, ladder, dashes, dots, surface, ladder:skewed, zebra:paired, zebra:bicolour, zebra:double, ladder:paired, dots;zebra, pictograms

For the missing ones, you can always edit the tags manually in SCEE.
