### ISSUE TITLE
Can't attach photo to note

### ISSUE THREAD

**Issue by pawlosck** [Helium314/SCEE#427]
I tried to add note with photo, but after taken photo, preview of photo is not visible in note (before sending to osm).
I checked option to save full size photo with EXIF, and it doesn't work too.

SCEE version: 52

**Comment by Helium314** [comment]
Not sure if you didn't answer the question on purpose, but it's quite useful to known: _Does it happen in normal StreetComplete?_

**Comment by pawlosck** [comment]
SC -> OK
SCEE -> NOT OK
Android version: 9.0 without modification
Hardware:Samsung Galaxy S8

Version 52 is the latest version in F-droid and in Aurora Store. I checked right now and I don't see any updates for SC and for SCEE.

**Comment by Helium314** [comment]
Latest is here: https://github.com/Helium314/SCEE/releases
Should be available on F-Droid on next repo update.
There was one change that might influence this bug. Though I wouln't expect this for Android 9...

It looks like for whatever reason the used camera app doesn't write the photo to the correct file (or maybe SCEE doesn't create the necessary file? But this should give you an error message.)

**Comment by pawlosck** [comment]
I installed latest version from github (52.2) and problem fixed. Issue can be closed.
Thanks for help.

PS. I see, you added preview for photos attached to note. Great work. I needed it, but my feature request in SC was rejected.

**Comment by Helium314** [comment]
> problem fixed

This is great! Honestly I would have no idea what to do to fix the bug, as the relevant code is the same as in StreetComplete.

> I needed it, but my feature request in SC was rejected.

Actually this was also added to StreetComplete some time ago, after initial testing in SCEE. See https://github.com/streetcomplete/StreetComplete/pull/4797

**Comment by pawlosck** [comment]
> > I needed it, but my feature request in SC was rejected.
> 
> Actually this was also added to StreetComplete some time ago, after initial testing in SCEE. See [streetcomplete#4797](https://github.com/streetcomplete/StreetComplete/pull/4797)

Strange. Previously, they told me that everything is ok and this feature is not needed, but now it was merged.
I stopped using SC few months ago after discovering EveryDoor app. Currently I am using Every Door and sometimes SCEE. SC/SCEE is great to answer for questions, but is not good solution to add new POI.
