### ISSUE TITLE
SCEE versioning (and divergence from upstream versioning)

### ISSUE THREAD

**Issue by mnalis** [Helium314/SCEE#432]
**Use case**
Currently it seems that SCEE versioning has diverged from upstream StreetComplete (probably due to lower cadence of upstream StreetComplete releases lately). 

While it is not an absolute requirement, I think it would make a lot of sense to **preserve upstream version in SCEE** versioning (both to avoid confusion e.g. _"bug is in SCEE 53.3 but not in StreetComplete 53.3, so it must be SCEE-specific"_, and to avoid technical issues like tag conflicts when merging both into one repository). Of course while doing that we should still note differences between different SCEE revisions of the same upstream (e.g. when upstream is slow to release) 

**Proposed Solution**

Perhaps something like _"53.1.3"_ or _"53.1EE3"_ (of some other variant like [Debian versioning](https://lewenberg.com/ikiwiki/debian/packaging/versioning/)) might work for SCEE versions based on StreetComplete _"53.1"_ upstream?

**Comment by Helium314** [comment]
Appending another version will require some changes to the changelog reader, which is not a huge effort, but too much for an issue I consider rather unimportant.

I think I'll switch to naming such versions e.g. 53.01.

**Comment by Helium314** [comment]
v54.0 is out, and version number is same again.
