### ISSUE TITLE
Allow permanently disabling the "Are you sure you checked this on-site" pop-up message

### ISSUE THREAD

**Issue by Atrate** [Helium314/SCEE#441]
**Use case**
The "Are you sure you checked this on-site" pop-up message is annoying, especially in higher-speed situations like public transit.

**Proposed Solution**
Add a settings switch to disable that permanently. Should be enough to add another OR condition in https://github.com/Helium314/SCEE/blob/62e35442bc038811833090c977c4ac68e5ff3c17/app/src/main/java/de/westnordost/streetcomplete/screens/main/CheckIsSurvey.kt#L28

**Comment by Helium314** [comment]
I'd rather do this via https://github.com/streetcomplete/StreetComplete/pull/4947

**Comment by Helium314** [comment]
implemented, will be in the next release
