### ISSUE TITLE
Add an option to not reset the map's tilt on changing from "follow-my-direction-of-travel" mode

### ISSUE THREAD

**Issue by Atrate** [Helium314/SCEE#442]
**Use case**
Occasionally when switching back and forth between free map browsing and location following I double-click the location button, which brings me into "follow-my-direction-of-travel" mode. After clicking the button again to quit that (annoying) mode, the map's tilt resets to 0, necessitating another re-tilting.

**Proposed Solution**
Add a settings switch to disable either the "follow-my-direction-of-travel" entirely or remove the tilt reset.

Line that resets the tilt in question:

https://github.com/Helium314/SCEE/blob/62e35442bc038811833090c977c4ac68e5ff3c17/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/LocationAwareMapFragment.kt#L77

**Comment by Helium314** [comment]
Actually the tilt should also change once you enable "follow-my-direction-of-travel" (to `PI/6`). Or is this close enough to the tilt you normally use so you don't really notice?

**Comment by Atrate** [comment]
Yup, I also notice the change (and it's slightly bothersome), though it's not *as* annoying as it's not as abrupt, the change to 0 tilt is a complete perspective change that kind of messes with my spatial awareness on the map for a few seconds

**Comment by Helium314** [comment]
Ok, then it would be better to have the setting disable navigation mode
