### ISSUE TITLE
Duplicate nodes created by shop overlay

### ISSUE THREAD

**Issue by Helium314** [Helium314/SCEE#445]
https://www.openstreetmap.org/node/11106952967 and https://www.openstreetmap.org/node/11106977243 were created at exactly the same position, and the user left a [note](https://www.openstreetmap.org/note/3827175) about the duplicate shop, so it was not intentional (would be really difficult anyway).

**How to Reproduce**
Unclear, probably add a node and have some issue with upload

**Expected Behavior**
SCEE creates only one node

**Does it happen in normal StreetComplete?**
Unclear, though maybe this is related to https://github.com/streetcomplete/StreetComplete/issues/4853

**Versions affected**
at least 53.32, probably others too

**Comment by mnalis** [comment]
Don't know if that is expected, but it might be interesting that while initial nodes were uploaded just a second apart, their IDs differ quite a lot (by `24276`). 

Might that signify that one was created earlier, but its upload failed half-way (i.e. after OSM received it, but before SC got confirmation back), so SC retried upload later?

**Comment by mnalis** [comment]
User commented on the note on request for more information with following clarification:

> Comment from [Falconbird21](https://www.openstreetmap.org/user/Falconbird21) about 10 hours ago
> I went to the shop and made changes offline. After I finished, I returned home to internet and uploaded my changes with a good internet connection.

**Comment by Helium314** [comment]
It's likely not an SCEE specific issue. If Android reacts slowly, you can press the plus button twice, and if you don't reaslize you will add the thing twice.

**Comment by mnalis** [comment]
> If Android reacts slowly, you can press the plus button twice, and if you don't reaslize you will add the thing twice.

While that is possibility, wouldn't that result in ids which are subseqent (or at lest very close by),  not ones which are tens of thousands apart? It still smells to more more like aborted upload / reupload issue.

> It's likely not an SCEE specific issue

I have no idea :shrug: 

Perhaps looking at [duplicate nodes](https://osmose.openstreetmap.fr/en/map/#zoom=8&lat=45.007&lon=17.715&item=1230%2C9xxx&level=1&issue_uuid=15cbcfc5-f2ed-d3e3-21f1-55599401a37e) might give some insights how often in which editors it is happening (so far most I've seen were iD and OsmAnd)

**Comment by Helium314** [comment]
If it only only happens with overlays, but also with SCEE _add node_, then it's likely an upload issue. Otherwise I would expect it's the issue I described above.

**Comment by matkoniecz** [comment]
Also, fixed upstream - can be fixed in SCEE by merging in upstream changes.

**Comment by Helium314** [comment]
Done already, just released SCEE 57.1
