### ISSUE TITLE
default log filename

### ISSUE THREAD

**Issue by mnalis** [Helium314/SCEE#448]
**Use case**
When one tries to save in `Settings` / `Log reader`, defualt log filename suggested is very generic. While one can always edit it, It would be nicer if it was by default such that it known it was SCEE log, and of what version it was. That would make it easier to find and reference them (esp. if one is trying to compare results of different SCEE versions to track down bug) and has more than one log

**Proposed Solution**
instead of naming it `log_1693052903538.txt`, name it `SCEE_v53.32_log_1693052903538.txt` or similar

**Comment by HolgerJeromin** [comment]
Or even with iso date instead of unix timestamp
`2009-06-30T18:30:00`
