### ISSUE TITLE
Add more roof shapes for the roof shape quest

### ISSUE THREAD

**Issue by Atrate** [Helium314/SCEE#450]
**Use case**
I don't know if it's just me living in a weird area, but I often find myself wanting to tag roofs like this, but being unable to because they aren't suggested by SC(EE):

![image](https://github.com/Helium314/SCEE/assets/26827848/95a482d7-2ab6-4ea9-939a-8923070e22c5)
![image](https://github.com/Helium314/SCEE/assets/26827848/0342f4fa-462f-45fa-99df-896e8d7eadbc)

**Proposed Solution**
Add more roof shapes to be used, basing on https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings#Roof

**Comment by Helium314** [comment]
Do you have a source for these images as vector graphics?
SC uses vector graphics for the roof images, so I assume they are  available somewhere...

**Comment by Atrate** [comment]
The graphics I linked here were made recently (today) by mxdanger on the OSM World Discord: https://discord.com/channels/413070382636072960/704832584328151040/1146933798429261936

**Comment by mxdanger** [comment]
Hi, someone to me about this issue. I’m the creator of the images. They are only raster and at the moment I have no plans for making vector versions. All of them can be found here: https://commons.wikimedia.org/wiki/Category:Files_by_Mxdanger

**Comment by Helium314** [comment]
Thanks, so it looks like the (very simlar looking) SC graphics come from somewhere/someone else.

With raster only the shapes won't make it to the roof color quest unfortunately (unless someone does the necessary re-coloring), but still can be added to the roof shape quest.
