### ISSUE TITLE
Wrong value `man_made=well` instead of `man_made=water_well` in "Add service building type" quest

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#453]
SCEE sets the tag `man_made=well` when answering "Add service building type" quest. According to JOSM validator this is deprecated and Osmose gives an error about this.

Reffering: https://github.com/Helium314/SCEE/blob/33bd89159cb03f35cadcce0f2b0a8acec89de975/app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingTypeForm.kt#L12C20-L12C20

[            "well", "reservoir_covered", "pumping_station" -> {](https://github.com/Helium314/SCEE/blob/33bd89159cb03f35cadcce0f2b0a8acec89de975/app/src/main/java/de/westnordost/streetcomplete/quests/service_building/AddServiceBuildingType.kt#L44)

Should be `water_well`

**Comment by Helium314** [comment]
Thanks!
Actually there is quite a bit more to update about the service building quest (extending selection, using `utility`, ...), but I never got around to do that.
