### ISSUE TITLE
SCEE 54.1 App won't start

### ISSUE THREAD

**Issue by chrisdebian** [Helium314/SCEE#457]
Hi, all.

I've just installed the new APK, 54.1, on a fully patched stock Pixel 6. I installed v54.1 over 54.0. This method has always worked with previous releases.

Now, when I try to start SCEE, from the app menu, nothing happens. I can't attach screenshots or show any output, because nothing happens. If I can submit logs for analysis, let m know how, and I'll upload them.

Hope this helps 

Chris
chris_debian

**Comment by HolgerJeromin** [comment]
Same here on android 13

**Comment by Helium314** [comment]
Same for me... weirdly enough it worked when I tested the debug version from Android Studio

**Comment by Helium314** [comment]
Looks like the upgrade to gradle 8 caused Proguard to become more aggressive, but only when building release versions (debug and release use the same Proguard rules).

**Comment by Helium314** [comment]
fixed in https://github.com/Helium314/SCEE/commit/e985190b4a877c8e78c133b5ce7917e1d5b80199

**Comment by chrisdebian** [comment]
Confirmed, 54.11 upgrade fixed this.
