### ISSUE TITLE
Quest(s?) for disabled parking capacity

### ISSUE THREAD

**Issue by wielandb** [Helium314/SCEE#463]
### General
I would like to implement a quest asking for `capacity:disabled=*` but I am opening this issue 'cause I am unsure if I should split it into two quests.

**Two quests:**
- (if `!capacity:disabled`) `capacity:disabled=yes/no`
- (if `capacity:disabled=yes`) `capacity:disabled=number`

**One quest:**
- (if `!capacity:disabled`) `capacity:disabled=no/number`

**Pros and cons for doing two quests:**
- Pros
  - Good if there disabled spaces but an inderterminable amount but you still want to add that there _are_ some
  - Easier to implement
  - People who are willing to check existence but not count can disable the follow-up quest
  - Writing "0" into the form when there is only one quest may be unintuitive 
- Cons
  - We edit the OSM object twice for something we could reasonably do in one go
  - More tedious to answer for the user 'cause they probably have to answer two quests   

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Metadata needed:** 

none

**Proposed UI:**

I would copy the UI from a yes/no quest and/or the bicycle parking capacity quest.

**Comment by wielandb** [comment]
My approach would be the following:

- Ask for a number with a "Other Answers" option to tag "yes"
- Default to `!capacity:disabled` for the quest selection but point the user to the possibility to change it to `!capacity:disabled or capacity:disabled = yes` in the default disabled message if they want to be asked to specify the precise amount
- Don't provide the "Other Answer" option if the element is already tagged with `capacity:disabled=yes`

**Comment by Helium314** [comment]
Sounds good!

**Comment by wielandb** [comment]
Fixed in #497
