### ISSUE TITLE
New Quest: What is the number of the ski slope here?

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#466]
### General
Affected tag(s) to be modified/added: [piste:ref](https://wiki.openstreetmap.org/wiki/Key:piste:ref)
Maybe to be discussed if `ref` or `piste:ref` should be set. https://openskimap.org/ will render both.
Question asked: **What is the number of the ski slope here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
See wiki: https://wiki.openstreetmap.org/wiki/Tag:piste:type%3Ddownhill
- [ ] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
This cannot be ensured, some ski slopes will not have a number.
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
Partially, of course, you have to be a "customer" of the ski resort and it can be answered only in winter.
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
During the research I noticed some ski slopes that have something like `piste:name=2 - Talabfahrt XYZ`. This is wrong, but should not have to be corrected by SCEE.
Therefore I would suggest the following filter: `way["piste:type"="downhill"][!"ref"][!"name"][!"piste:name"][!"piste:ref"]`
Overpass Link: https://overpass-turbo.eu/s/1CoH

**Proposed UI:**
Similar to the house number Quest.
- It should be possible to enter numbers and letters (7a)
- If `piste:difficulty` is stored, you could display a blue, red or black circle in the background instead of the blue frame in the house number quest.
- Ideally, the quest is displayed only in winter. Isn't there already a function for the grit bins for this?

**Comment by HolgerJeromin** [comment]
I would add "other" menu entry:
* This is only a connection and change to: `piste:type=connection`

**Comment by Helium314** [comment]
Sounds fine, and re-using the address form should make most of the implementation relatively simple.

> Ideally, the quest is displayed only in winter. Isn't there already a function for the grit bins for this?

There is a quest whether grit bins are seasonal, but it's displayed all year long.
Maybe as a very simple implemetation the quest could be made so that it's not applicable to any element if it's not winter. With data being cleaned up after 2 weeks (be default), this should be acceptable.
