### ISSUE TITLE
New Quest: For which sport is this guidepost intended? (information=guidepost/route_marker)

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#467]
Reference: https://github.com/streetcomplete/StreetComplete/issues/4758
And: https://github.com/streetcomplete/StreetComplete/issues/5208

### General
Affected tag(s) to be modified/added: The common and established tags for sports (like `hiking`, `bicycle`, `ski`, ...
Question asked: **For which sport is this guidepost intended?**
The goal is to determine the particular sport(s) for a guidepost or routemarker.

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

Data from Jan 18:
Number of matched nodes in Austria: 14310
Number of matched nodes in Germany: 37408
Number of matched nodes in Switzerland: 7956
Number of matched nodes in United States: 10388

Overpass-Link: https://overpass-turbo.eu/s/1qhA

### Ideas for implementation

**Element selection:** 
```
nodes and 
["tourism"="information"] and
["information"="guidepost"] or ["information"="route_marker"] and
[!"hiking|bicycle|mtb|climbing|horse|nording_walking|ski|inline_skates|running"] and
[!"disused"][!"guidepost"]
```

There are certainly more sports to filter. Here are the ones that are known to me so far. Please comment if I've missed one!

**Concerns:** 

- It often happens that there are several signs for different sports hanging on a pole. Since the ref=* is usually also different, I have preferred to enter the nodes separately. This would not be possible in the Quest. A multiple selection would then have to be stored using a semicolon.
- There are different ways to tag the sport. Either with "hiking=yes" or "guidepost=hiking" or "guidepost:hiking=yes". Based on an evaluation of taginfo, the first one in the list is the most used.
- There is no "no" answer. But from my point of view, each signpost has a specific sport (at least from my regional experience). If the user can not say it it definitely needs a "can't say" answer option if it is not answerable to the user.
- If there is no specific sport displayed on the guidepost, there is `guidepost=simple` in the wiki: https://wiki.openstreetmap.org/wiki/Tag%3Aguidepost%3Dsimple

**Proposed UI:**

- Simple image selection or icon selection as in the recycling quest.
- You should be able to specify "This is a routemarker" as an alternative answer. This answer is more for experienced users, but it makes the usability easier and the effort is manageable.

** Possible Quest Filter
```
nodes with
          tourism = information
          and (information ~ guidepost|route_marker|map)
          and (!guidepost and !disused
          and (
                    !hiking or !bicycle or !mtb or !climbing or !horse or !nording_walking or! ski or !inline_skates or !running
          )
```

**Comment by jonpsp** [comment]
I think I would prefer to use "activity" rather than "sport". I do not do any form of sport, but I do use these signs when walking or cycling.

**Comment by qugebert** [comment]
Maybe for maps too? At least in my area, most maps also display hiking/biking routes.

**Comment by Helium314** [comment]
> It often happens that there are several signs for different sports hanging on a pole. Since the ref=* is usually also different, I have preferred to enter the nodes separately. This would not be possible in the Quest. A multiple selection would then have to be stored using a semicolon.

Since the quest is not about `ref` I think it's fine. When someone wants to add a `ref` (using a different editor), they can still split the guidepost into multiple nodes.

>There are different ways to tag the sport. Either with "hiking=yes" or "guidepost=hiking" or "guidepost:hiking=yes". Based on an evaluation of taginfo, the first one in the list is the most used.

And this is by a huge margin, so I agree on using `<sport>=yes`

> If the user can not say it it definitely needs a "can't say" answer option if it is not answerable to the user.

While it's preferable, I don't think this is absolutely necessary. The quest could be added without such option, and maybe it can be added later based on user feedback (if it occurs to frequently).

> Simple image selection or icon selection as in the recycling quest.

A simple text selection like for the seating quest would be fine too.

**Comment by qugebert** [comment]
I guess simple text selection won't work, as it's single choice but some guideposts are for multiple activities

**Comment by mnalis** [comment]
Yes, I too think it should be multiple-answer (like in e.g. recycling quest). For example, some routes (and their signposts) are for both cycling and hiking (or might have different summer/winter purposes)

**Comment by qugebert** [comment]
> Okay, here is super rough mockup how I imagine the Quest. A simple text selection would also work. Finding harmonious, matching icons for each sport is really a pain.
> <img alt="" width="25%" height="25%" src="https://user-images.githubusercontent.com/3351668/278241603-aa9ea546-e680-4ad7-b7c5-ce4d676484dd.png">

So are these icons available in a compatible license? If so, could you please send me these? This would make it much easier for me :)

**Comment by Helium314** [comment]
> I guess simple text selection won't work, as it's single choice but some guideposts are for multiple activities

Making a form that allows multiple selections should be simple.
But the recycling-UI based version already looks really good in my opinion.

I'm somewhat opposed to adding photos when it's not necessary. Images already take more than 50% of the APK size, that fraction will likely increase anyway.

**Comment by mnalis** [comment]
> If there is no specific sport displayed on the guidepost, there is guidepost=simple in the wiki: https://wiki.openstreetmap.org/wiki/Tag%3Aguidepost%3Dsimple

Would that be provided as a regular answer (with what picture? questionmark icon?) or as `other answer`?

**Comment by qugebert** [comment]
No, nothing done yet.
