### ISSUE TITLE
Turn restriction overlay: stop direction hard to see

### ISSUE THREAD

**Issue by roptat** [Helium314/SCEE#469]
Wgen selecting a stop, it is possible to select the direction for which the tign applies. However, it's not possible to distinguish the selected and unselected directions.

![IMG_20231027_110222](https://github.com/Helium314/SCEE/assets/24874997/6c51c21b-fc40-46f5-b44b-93aede8f2063)

I can see a very small difference in color, but it's not contrasted enough. At first sight, I thought no direction was selected.

**How to Reproduce**

Select turn restriction overlay, zoom in on a stop, click on it. This only happens with light theme.

**Expected Behavior**

The two arrows should be more contrasted to make it possible to distinguish the currently selected direction.

**Does it happen in normal StreetComplete?**

No, turn restriction overlay is specific to SCEE.

**Versions affected**

54.12 from fdroid

**Comment by Helium314** [comment]
Should be simple to fix, will do before releasing the next version.

I changed the title, as from text and description it's clear that the direction is not actually invisible.

**Comment by roptat** [comment]
Thanks!
