### ISSUE TITLE
New Quest: What is the `via_ferrata_scale` on this path?

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#479]
### General
Affected tag(s) to be modified/added: [via_ferrata_scale](https://wiki.openstreetmap.org/wiki/Key:via_ferrata_scale)
Question asked: **What is the via ferrata scale on this path?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [ ] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
ways with (
highway = via_ferrata
and !via_ferrata_scale
)
```

**Proposed UI:**
Option 1:
Image based quest (like smoothness) with reference images

Option 2:
Make it simple and just show a selection of 0 to 6

## Verifiability and Subjectivity
It's a very controversial Tag, but I would leave it to the experts to activate this quest.

**Comment by Helium314** [comment]
I'm not sure whether the quest is worth implementing, there seem to be only a few hundred applicable elements.
(interestingly `via_ferrata_scale` has more uses than `highway=via_ferrata`)
But as the work isn't done by me it's still acceptable for SCEE.

I think the smoothness style with descriptions would be useful, as even experienced people with might not remember all the details. Showing the French & German scales could also be useful.

Further there should be a clear warning in the _quest disabled message_ about requiring experience.

**Comment by Helium314** [comment]
For the MTB scale I think that it should rather be an overlay, see https://github.com/streetcomplete/StreetComplete/issues/1850#issuecomment-1762815653
