### ISSUE TITLE
Button to switch map background

### ISSUE THREAD

**Issue by contrapunctus-1** [Helium314/SCEE#481]
**Use case**
I'm looking for a no-configuration mobile application for new contributors, regardless of how heavily mapped (or completely unmapped) their region is.

Editing in unmapped regions requires aerial imagery, which is missing in StreetComplete but present in SCEE. However, it is hidden behind two menus, making it less accessible.

**Proposed Solution**
Since SCEE only has two imagery layers - "map" and Esri (at least on F-Droid) - a button could be added to the main screen (at the bottom-left or bottom-right) which could switch between the two layers. This is similar to Every Door.

If more layers exist/are added, the "Select background type" menu item could be changed to "Select aerial imagery", and the "map" item removed from it. Alternatively, the imagery button could cycle through available imagery layers.

**Comment by mnalis** [comment]
In the intend use that your users use SCEE on-the-ground, or from home?

If you need aerial imagery, I'd guess is might be from home, but for _"completely unmapped"_ regions, SCEE might be lacking for your use case -- you can only work with points, so there is no support for adding ways (like roads, paths, rivers...) nor areas (like pitches, parks, playgrounds, buildings...)

Also note (if not being mapped on the ground) that SCEE currently will asks users `Are you sure you checked this on site? Only information that was found on survey should be entered`  and tag all their changesets with `source=survey` (which would be misleading in that case for reviewers - but that is separate issue which should be changed too IMHO)

---

As for the adding it as a separate button, I guess that maybe there might be an option to that, but SCEE is already using quite a bit of screen for its UI, leaving little space for the map (especially on the smaller screens).

**Comment by Helium314** [comment]
I don't intend to add another button, it's already in the quick settings anyway.
As for _no-configuration_, I won't enable the quick settings by default, as SCEE is intended to be close to StreetComplete without any further configuration.

There is already the possibility of customizing the background imagery, i.e. changing the URL.
