### ISSUE TITLE
New Quest: What is the difficulty of this piste? `piste:difficulty`

### ISSUE THREAD

**Issue by mcliquid** [Helium314/SCEE#484]
### General
Affected tag(s) to be modified/added: [piste:difficulty](https://wiki.openstreetmap.org/wiki/Key:piste:difficulty)
Question asked: **What is the difficulty of this piste?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
ways with piste:type ~ downhill|nordic
and !piste:difficulty
and piste:grooming = classic
```
`piste:type` can be extended to hike and skitour, but maybe in a later step.
`piste:grooming` is optional - will decrease the selection of course

**Metadata needed:** 

**Proposed UI:**
There are three options.
1. AbstractOsmQuestForm
Only three buttons with "easy", "intermediate" and "advanced". However, this would require the quest to be limited to Europe / the Alps.

2. AListQuestForm
Simple Text Selection. Could contain more values, but in Europe users would be confused by entries such as "Novice" (green).

3. AImageListQuestForm
Showing images (wikimedia) or icons of colored piste signs to select.
Red example: https://commons.wikimedia.org/wiki/File:Red_piste_Fred_in_Flaine.jpg
Black example: https://commons.wikimedia.org/wiki/File:Black_piste_Agate_in_Flaine.jpg

Personally, a simple selection as buttons would be enough for me. One would only need a single click to complete the quest. I would simply use "blue", "red" and "black" as values.
**Which do you all prefer?**

I would start with this one before going over to https://github.com/Helium314/SCEE/issues/466

**Comment by mnalis** [comment]
I'm not going to be of much use here, as I never visited even one of those skiing-things :smile: so I'm quite unlikely to use this quest; but just a note that several quests (like fire hydrant, maxspeed etc) do offer **_different pictures / signs for different countries_**; so perhaps that might be an option here too? (e.g. have one list for Europe, one for USA, and general one for everybody else? or what have you)

**Comment by HolgerJeromin** [comment]
I (long term ski sportsman) would go for color text only.

**Comment by Helium314** [comment]
> Applies to a reasonable number of map data

Not sure, the current filter matches only ~1400 elements in central Europe. Removing `piste:grooming = classic` increases the number considerably.

> Proposed UI

Since it's usually color coded, I think adding colors (just icons, maybe colored circles) would be good. This allows for showing different icons appropriate for the area. Though there is no need to implement this, the quest can be limited to Europe instead.

**Comment by Helium314** [comment]
> What would be the best quest-blueprint to start this quest?

A single-column `AImageListQuestForm` with `imageSelector.cellLayoutId = R.layout.cell_labeled_icon_select_with_description` might be fine

**Comment by Helium314** [comment]
I think `cell_labeled_icon_select_with_description` should also work outside a grouped image list form
