### ISSUE TITLE
How power line is attached to support

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Helium314/SCEE#492]
### General
Affected tag(s) to be modified/added: [line_attachment](https://wiki.openstreetmap.org/wiki/Key:line_attachment)
Question asked: **How power line is attached on this support?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [X] 🚧 To be added tag is established and has a useful purpose
- [X] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [X] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [X] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
- Power pole and power tower without line_attachment key
- This quest is not to tag complex configurations (case where we have 2 differents line_attachements in same node)

**Metadata needed:** 
No local metadata

**Proposed UI:**
Photos or drawings

One proposition has already proposed on main repo #4825

**Comment by Helium314** [comment]
That would certainly be acceptable, but I think it would be good to have some decision about the quest in SC first. Currently it hasn't been declined, and implementing quests in SC is preferable as it reaches far more users.

**Comment by Jean-BaptisteC** [comment]
Thanks for your feedback, our quest has been accepted on main repo with just more arguments :)
I close this issue
