### ISSUE TITLE
Bug in Speedlimit Quest in SCEE but not in SC

### ISSUE THREAD

**Issue by Langlaeufer** [Helium314/SCEE#509]
If you are ask for the maxspeed on roads in Germany Citys and you answer with 
* **no sign**
* yes really no sign
* **urban**

Then SCEE 
* sets maxspeed:type= DE:urban (even if it already exists)
* it  does not set maxspeed to 50

**The Bug is**
* SCEE (still) asks for speed, even when the **maxspeed:type=DE:urban** is already set.
* SCEE uploads the ways even with no (real) change in "maxspeed:type"

SCEE is not asking when maxspeed:type = DE:rural is present.

**Does it happen in normal StreetComplete?**
I checked with normal SC: SC is not asking for maxspeed when maxspeed:type is already present.

**Versions affected**
Current and previous versions

**Comment by Langlaeufer** [comment]
Example for uploading not changed ways:
https://osmlab.github.io/osm-deep-history/#/way/25459525
the last 4 changes

**Comment by Helium314** [comment]
The default filter as of v56.1 excludes `maxspeed:type`, so the quest should not be asked. See https://github.com/Helium314/SCEE/blob/3e9ae9162d418faea668b3e2991e55f216c649dc/app/src/main/java/de/westnordost/streetcomplete/quests/max_speed/AddMaxSpeed.kt#L19 and https://github.com/Helium314/SCEE/blob/3e9ae9162d418faea668b3e2991e55f216c649dc/app/src/main/java/de/westnordost/streetcomplete/osm/Maxspeed.kt#L6-L10

Can you reproduce it for all ways? There was a (recently fixed) issue that quests sometimes are asked over and over again, but only for single elements: https://github.com/streetcomplete/StreetComplete/issues/4258
If you can reproduce it for all ways (I cannot), then my only idea is that you might not use the default element filter.

> it does not set maxspeed to 50

SC __does__ set maxspeed to 50 in that case?

**Comment by Langlaeufer** [comment]
Yes, "Does not set speedlimit" is not the bug. SC also do not set speedlimits.

I can repoduce it with ever way with maxspeed:type=DE:urban and without maxspeed=50)

**Comment by Helium314** [comment]
> only maxspeed:type=DE:urban but not maxspeed:type=DE:rural seams to be affected

Are you using the default element filter? I see no way of this happening with the default filter, as _anything_ with `maxspeed:type` should be excluded. If something is broken, I would expect the quest to be asked for any value of `maxspeed:type`.

**Comment by Langlaeufer** [comment]
> Are you using the default element filter?
I don't know.
How can I change the element filter?

**Comment by Langlaeufer** [comment]
I have the problem on two different devices, but I ex-/imported the settings.

**Comment by Helium314** [comment]
Changing the filter does not affect the already existing quest.
Did you re-scan for quests after resetting the filter? Alternatively you can enable _dynamic quest creation_ in the _quests_  setting section.

**Comment by Langlaeufer** [comment]
After resetting the Quest defaults an re-scan for quest the problem is solved. 
Thanks for the fast help.
