### ISSUE TITLE
Possibility to use preset also when editing existing node

### ISSUE THREAD

**Issue by Filip10** [Helium314/SCEE#511]
**Use case**

If I want to edit existing node and add things autommatically from preset which is not available right now.
Like there is pharmacy Dr. Max in reality, but in map it has old name. So I want to add things from preset like operator and name automatically from preset.

**Proposed Solution**

When there is "SHOW/EDIT TAGS" option, there could be a new option to select from preset. Or new button in edit tags mode.

**Comment by mnalis** [comment]
If you open `Shop overlay` in SCEE, select an existing POI (or create new one), and click on **type** of a shop (not name!) and type a _name_ of brand/chain there that exists in [NSI](https://wiki.openstreetmap.org/wiki/Name_Suggestion_Index), it will show in italics, and upon selecting it it will automatically fill-in multiple tags for it. 

If some brand/chain is missing, you would add it at https://nsi.guide/ of course (but [Dr.Max](https://nsi.guide/index.html?t=brands&k=amenity&v=pharmacy&tt=dr.%20max) is already present)

**Comment by Filip10** [comment]
Ooh, nice, thank you, I was using my own overlay only for tag shop and never tried default one. Thank you.
