### ISSUE TITLE
Wrong icon when completing quest

### ISSUE THREAD

**Issue by Martinligabue** [Helium314/SCEE#515]
When solving a quest that's not present in standard sc the icon going away, during moving animation, shows the red note icon instead of the quest icon
**How to Reproduce**

Solve any quest only present in scee and pay attention to the animation 
**Expected Behavior**

It should continue using the quest icon 
**Does it happen in normal StreetComplete?**

N/A
**Versions affected**

13, 56.1

**Comment by mnalis** [comment]
Hm, does it always happen? For all SCEE-only quests or only some? 
Do you have any specific example where it is reproducible?

Here is random example on my Android 14 with SCEE 56.1 and it looks normal to me:

https://github.com/Helium314/SCEE/assets/156656/30cedd78-b221-4e92-8dc7-cbddac1edac1

**Comment by Helium314** [comment]
I also cannot reproduce this. I tried a few quests, and either I see no animation at all (not related to quest type, possibly phone is too slow) or it has the correct icon.

**Comment by Martinligabue** [comment]
I can't reproduce either anymore, it might be some rare glitch, so I'd close this until I get it again if I understand how or why
