### ISSUE TITLE
publish beta versions on F-Droid

### ISSUE THREAD

**Issue by tiptoptom** [Helium314/SCEE#517]
Would you also agree to other people triggering a beta update for SCEE via mr at F-Droid?

https://github.com/streetcomplete/StreetComplete/issues/5494

**Comment by Helium314** [comment]
I don't know how it's handled currently. Are SCEE beta versions really not available on F-Droid?

**Comment by tiptoptom** [comment]
No, they are excluded through [this expression](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.westnordost.streetcomplete.yml#L1247).

**Comment by Helium314** [comment]
Ok, then it's fine. Though SCEE beta releases are relly rare anyway.
