### ISSUE TITLE
GNSS not well synchronized in 57.1

### ISSUE THREAD

**Issue by goldfndr** [Helium314/SCEE#524]
Between the 57.0 and 57.1 release of SCEE, tracking of GNSS on-screen became randomly sporadic instead of consistent. See https://photos.app.goo.gl/tuwq8AehAT6eHjdv9 for a side-by-side screen capture (~20 seconds, 12 MB) with normal StreetComplete 57.1 simultaneously running. Possibly platform specific?

**How to Reproduce**
Uninstall SCEE then install SCEE 57.0 from GitHub's release apk. Accept defaults until *on map*. Walk/ride about, observe consistency of *the blue dot's* corresponding movement. Install 57.1 from GitHub's release apk over 57.0. Move about, observe *the blue dot* often doesn't change position on the map.

**Expected Behavior**
*The blue dot* should change position each time a GNSS update occurs.

**Does it happen in normal StreetComplete?**
No.

**Versions affected**
Android 14 (both security patch level 2024-02-01 and 2024-03-01) on a Samsung Galaxy Z Fold3; SCEE 57.1

**Comment by Helium314** [comment]
Is the issue only happening when installing 57.1 over 57.0?

> The blue dot should change position each time a GNSS update occurs.

In that case you should open an issue in SC repo. Position is only updated when this returns true:
https://github.com/streetcomplete/StreetComplete/blob/7236c273f3f3b069a32d14f7ceb608ea56f86fc0/app/src/main/java/de/westnordost/streetcomplete/util/location/FineLocationManager.kt#L115-L125
(SCEE uses the same, with a small change that can only result in returning `true` more often

**Comment by goldfndr** [comment]
No. The issue also occurs on a completely new install (SCEE uninstalled first).

Also reproducible on an LG V50 Thinq on Android 10: whether a fresh new install or an update from SCEE 57.0, SCEE 57.1 doesn't track well. SCEE 57.0 on the LG V50 Thinq does track well.

Again, I'm unable to reproduce it in SC 57.1 (see video), so I don't think an issue in that repo would be appropriate.

**Comment by goldfndr** [comment]
Oof. I didn't realize that https://github.com/streetcomplete/StreetComplete/pull/5516 was merged after SC 57.1.

**Comment by Helium314** [comment]
> Oof. I didn't realize that [streetcomplete#5516](https://github.com/streetcomplete/StreetComplete/pull/5516) was merged after SC 57.1.

I think this should not make any difference though.

I didn't notice any issues with SCEE 57.1 on my phone, but I'll have a closer look next time I use it...

**Comment by Helium314** [comment]
> Oof. I didn't realize that https://github.com/streetcomplete/StreetComplete/pull/5516 was merged after SC 57.1.

But you're right. It's in SC only in the next release, but in SCEE 57.1 and indeed appears to be the problem.

**Comment by Helium314** [comment]
Should be fixed with https://github.com/streetcomplete/StreetComplete/commit/83d7991ca037e3b02be0566b67b98ffd9132058a

**Comment by Langlaeufer** [comment]
As workaround you can use the app "GPS Connected" in the background.
