### ISSUE TITLE
See object history on osm.org

### ISSUE THREAD

**Issue by Filip10** [Helium314/SCEE#526]
![Screenshot_20240402_105541_SCEE](https://github.com/Helium314/SCEE/assets/25711588/3d064908-f4b8-44b5-99a9-8eb2ea38347f)

**Use case**

When you want to see a history of object is good to click on object and click on something like "See object history on OSM" if the object was added by legit user, or just one time mapper. Now I need to go to Vespucci, download area and just then I can open it in browser. There is not other option to do it straight via openstreetmap.org on mobile. Just if I switch to PC version and try to edit the map.

**Proposed Solution**

Just add a new row in section which screenshot I have attached.

**Comment by Helium314** [comment]
I would like to avoid adding yet another row here (for some quests there are way too many already).
Checking the history to see the user who added the element mostly makes sense when editing tags, so it could also be added in tag editor.

**Comment by Filip10** [comment]
Okay. For me it doesn't matter where it would be. But I think it is nice thing to have.

**Comment by mnalis** [comment]
Ah yes, I also wanted that  (but keep forgetting to request it)

Tag editor currently shows last edited date (which is very useful); my idea was to also have it show object id (e.g. _"node 12345"_ or _"way 56789"_), and make that id a link - so it leads to `https://www.openstreetmap.org/node/12345` where history, user, changeset etc. could be easily accessed
