### ISSUE TITLE
Street furniture ref quest

### ISSUE THREAD

**Issue by FloEdelmann** [Helium314/SCEE#531]
### General
Affected tag(s) to be modified/added: [ref](https://wiki.openstreetmap.org/wiki/Key:ref)
Question asked: **What’s the identification number here?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
  → it varies from region to region which objects usually have a signed reference code. Therefore, it's definitely not suitable for upstream StreetComplete, but maybe it's a good fit for SCEE?
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 

```
nodes, ways with
  (
    building = service and power = substation
    or man_made = street_cabinet
    or highway = street_lamp
    or emergency = fire_hydrant and fire_hydrant:type = underground and fire_hydrant:diameter:signed != no
  )
  and !ref
  and ref:signed != no
```

**Metadata needed:** None

**Proposed UI:** Like other ref quests

**Comment by Helium314** [comment]
Should be fine in principle.
Though I wonder whether we could merge this with some of the ref quest(s)... most of them do the same, just with a different icon. The filter can be adjusted in SCEE anyway, for kicking out unwanted things.

**Comment by FloEdelmann** [comment]
> most of them do the same, just with a different icon

and with a different changeset comment. I currently use the `AddAccessPointRef` quest with an edited element filter, but "Determine emergency access point refs" is quite confusing if it is street cabinets and street lanterns instead :sweat_smile: 

Also note that the `AddBusStopRef`, `AddFireHydrantRef` and `AddPostboxRef` quests are never shown in Germany. Is there some way to lift that restriction in SCEE? Then at least for fire hydrants I could use the existing quest and adjust its element filter.

**Comment by Helium314** [comment]
> Is there some way to lift that restriction in SCEE?

Currently not. A setting could be added, but I think in many cases allowing users to answer all quests is not a good idea (e.g. housenumber quest in Italy).

Maybe a quest with generic comment can be done?
The subway and guidepost in SCEE could be adjusted... but they both use specific disabled messages.

Or just add the new one in a more generic way, so there is no / less need for yet another ref quest.
