### ISSUE TITLE
GPS Position Update 

### ISSUE THREAD

**Issue by Langlaeufer** [Helium314/SCEE#534]
The GPS position is only updated sporadically. Position jumps at irregular, very large intervals >> 10 s.
The update rate settings doesn't have any effect on the behavior.
Other apps such as SC and OSMAnd are not affected by the issue - means Positioning on my phone is working well.

**How to Reproduce**
In all settings I tried: e.g. in standard configuration after install on my Samsung Galaxy A54  Android 14 One Ui 6.0

**Expected Behavior**
Smooth Position Update at least every second.

**Does it happen in normal StreetComplete?**
No, in SC 57.1 Positioning works fine

**Versions affected**
SCEE 57.1 

**Workaround**
The behavior can be corrected with the utility app “GPS Connected”.

**Comment by riQQ** [comment]
See also #524

**Comment by mnalis** [comment]
Already fixed in code,  but one has to wait for next release to actually get the fix.

So, we probably should keep this issue open until the next SCEE release happens (it is taking some time, as there is major work going in upstream StreetComplete), so others will find it more easily.

**Comment by Helium314** [comment]
I don't intend to keep solved issues open, but I added the suggestion to search open and closed issues to the top of the bug and feature request issue templates.
